<?php
/**
 * STRUCTIFY - v6 (The Ultimate Dual-Threat)
 * Supports ZIP Generation AND Bash Script Export with Smart Injections.
 */

function generateBoilerplate($path, $framework) {
    $filename = basename($path);
    $ext = strtolower(pathinfo($filename, PATHINFO_EXTENSION));
    $className = pathinfo($filename, PATHINFO_FILENAME);

    // --- 1. CODEIGNITER 4 ---
    if ($framework === 'ci4' && $ext === 'php') {
        $dirPath = dirname($path);
        $namespaceParts = explode('/', $dirPath);
        if (isset($namespaceParts[0]) && $namespaceParts[0] === 'app') $namespaceParts[0] = 'App';
        $namespaceParts = array_filter($namespaceParts, function($p) { return $p !== '.' && !empty($p); });
        $namespace = implode('\\', $namespaceParts);

        if (strpos($path, 'Controllers/') !== false) return "<?php\n\nnamespace $namespace;\n\nuse App\Controllers\BaseController;\n\nclass $className extends BaseController\n{\n    public function index()\n    {\n        return view('welcome_message');\n    }\n}\n";
        if (strpos($path, 'Models/') !== false) {
            $tableName = strtolower(str_replace('Model', '', $className)) . 's';
            return "<?php\n\nnamespace $namespace;\n\nuse CodeIgniter\Model;\n\nclass $className extends Model\n{\n    protected \$table            = '$tableName';\n    protected \$primaryKey       = 'id';\n    protected \$allowedFields    = [];\n}\n";
        }
        return "<?php\n\nnamespace $namespace;\n\n// TODO: Implement $className\n";
    }

    // --- 2. LARAVEL ---
    if ($framework === 'laravel' && $ext === 'php') {
        $dirPath = dirname($path);
        $namespaceParts = explode('/', $dirPath);
        if (isset($namespaceParts[0]) && $namespaceParts[0] === 'app') $namespaceParts[0] = 'App';
        $namespaceParts = array_filter($namespaceParts, function($p) { return $p !== '.' && !empty($p); });
        $namespace = implode('\\', $namespaceParts);

        if (strpos($path, 'Controllers/') !== false) return "<?php\n\nnamespace $namespace;\n\nuse Illuminate\Http\Request;\nuse App\Http\Controllers\Controller;\n\nclass $className extends Controller\n{\n    public function index(Request \$request)\n    {\n        //\n    }\n}\n";
        if (strpos($path, 'Models/') !== false) return "<?php\n\nnamespace $namespace;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\n\nclass $className extends Model\n{\n    use HasFactory;\n\n    protected \$fillable = [];\n}\n";
        return "<?php\n\nnamespace $namespace;\n\n// TODO: Implement $className\n";
    }

    // --- 3. REACT (JS/TS) ---
    if ($framework === 'react' && in_array($ext, ['js', 'jsx', 'ts', 'tsx'])) {
        $compName = str_replace(['-', '_'], ' ', $className);
        $compName = str_replace(' ', '', ucwords($compName)); 
        return "import React from 'react';\n\nconst $compName = () => {\n  return (\n    <div className=\"$className-wrapper\">\n      <h1>$compName Component</h1>\n    </div>\n  );\n};\n\nexport default $compName;\n";
    }

    // DEFAULT FALLBACKS
    if (in_array($ext, ['js', 'ts', 'css', 'scss'])) return "/* File generated by Structify */\n";
    if (in_array($ext, ['html', 'xml'])) return "\n";
    if ($ext === 'php') return "<?php\n\n// File generated by Structify\n";
    return ""; 
}

// --- BACKEND: Handle the Form Submission ---
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['tree_text'])) {
    
    $rawText = $_POST['tree_text'];
    $framework = $_POST['framework'] ?? 'none';
    $action = $_POST['action'] ?? 'zip'; // NEW: Determine which button was clicked!
    
    $lines = explode("\n", $rawText);
    $structure = [];
    $pathStack = [];
if (count($lines) > 500) {
    die("Error: For performance reasons, trees are limited to 500 lines.");
}
    foreach ($lines as $line) {
        // Strip #, (, and // comments
        $lineCleaned = preg_replace('/\s*[\(#].*$/', '', $line);
        $lineCleaned = rtrim($lineCleaned);

        if (!preg_match('/^([│├└─\s ]*)(.*)$/u', $lineCleaned, $matches)) continue; 

        $prefix = $matches[1];
        $name = trim($matches[2]);
        $name = rtrim($name, '/');
        $name = trim($name);

        if (empty($name)) continue;

        $visualIndent = mb_strlen($prefix, 'UTF-8');
        $isFile = (strpos($name, '.') !== false);

        while (!empty($pathStack) && end($pathStack)['indent'] >= $visualIndent) {
            array_pop($pathStack);
        }

        $currentNode = ['name' => $name, 'indent' => $visualIndent, 'is_file' => $isFile];
        $pathStack[] = $currentNode;
        
        $structure[] = [
            'path' => implode('/', array_column($pathStack, 'name')),
            'is_file' => $isFile
        ];
    }

    if (empty($structure)) die("Could not parse any structure.");

    // ==========================================
    // ACTION: BASH SCRIPT EXPORT
    // ==========================================
    if ($action === 'bash') {
        $bashScript = "#!/bin/bash\n\n";
        $bashScript .= "echo \"🚀 Structify: Building your architecture...\"\n\n";

        // 1. Create all directories first using mkdir -p
        $dirs = [];
        foreach ($structure as $item) {
            if (!$item['is_file']) {
                $dirs[] = '"' . $item['path'] . '"';
            } else {
                $dirs[] = '"' . dirname($item['path']) . '"'; // Ensure parent dir exists for files
            }
        }
        $dirs = array_unique($dirs);
        $dirs = array_filter($dirs, function($d) { return $d !== '""' && $d !== '"."'; });
        
        if (!empty($dirs)) {
            $bashScript .= "# Create directories\n";
            $bashScript .= "mkdir -p " . implode(" ", $dirs) . "\n\n";
        }

        // 2. Create files and inject boilerplate
        $bashScript .= "# Create files and inject code\n";
        foreach ($structure as $item) {
            if ($item['is_file']) {
                $content = generateBoilerplate($item['path'], $framework);
                if (empty($content)) {
                    $bashScript .= "touch \"{$item['path']}\"\n";
                } else {
                    $bashScript .= "cat << 'EOF' > \"{$item['path']}\"\n";
                    $bashScript .= $content;
                    if (substr($content, -1) !== "\n") $bashScript .= "\n";
                    $bashScript .= "EOF\n\n";
                }
            }
        }

        $bashScript .= "echo \"✅ Architecture built successfully!\"\n";

        header('Content-Type: text/x-shellscript');
        header('Content-Disposition: attachment; filename="structify_build.sh"');
        header('Content-Length: ' . strlen($bashScript));
        header('Pragma: no-cache');
        header('Expires: 0');
        echo $bashScript;
        exit;
    }

    // ==========================================
    // ACTION: ZIP FILE GENERATION (Default)
    // ==========================================
    $zip = new ZipArchive();
    $zipFileName = 'structify_project_' . time() . '.zip';
    $tempDir = __DIR__ . '/temp';
    if (!is_dir($tempDir)) mkdir($tempDir, 0777, true);
    $tmpFilePath = $tempDir . '/' . $zipFileName;

    if ($zip->open($tmpFilePath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== TRUE) die("Failed to create ZIP file.");

    foreach ($structure as $item) {
        if ($item['is_file']) {
            $fileContent = generateBoilerplate($item['path'], $framework);
            $zip->addFromString($item['path'], $fileContent);
        } else {
            $zip->addEmptyDir($item['path']);
        }
    }
    $zip->close();

    header('Content-Type: application/zip');
    header('Content-Disposition: attachment; filename="' . basename($zipFileName) . '"');
    header('Content-Length: ' . filesize($tmpFilePath));
    header('Pragma: no-cache');
    header('Expires: 0');
    readfile($tmpFilePath);
    
    unlink($tmpFilePath);
    exit;
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Structify - Smart Architecture Builder</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        textarea { font-family: 'Courier New', Courier, monospace; white-space: pre; overflow-wrap: normal; overflow-x: auto; }
        #preview_container::-webkit-scrollbar { width: 8px; height: 8px; }
        #preview_container::-webkit-scrollbar-track { background: transparent; }
        #preview_container::-webkit-scrollbar-thumb { background: #cbd5e1; border-radius: 4px; }
    </style>
</head>
<body class="bg-slate-50 min-h-screen text-slate-800 font-sans">

    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
        <header class="mb-8 text-center">
            <h1 class="text-4xl font-extrabold tracking-tight text-slate-900 mb-2">Structify</h1>
            <p class="text-lg text-indigo-600 font-medium">The only folder generator with context-aware code injection.</p>
        </header>

        <div class="bg-white rounded-2xl shadow-xl border border-slate-200 overflow-hidden">
            <div class="grid grid-cols-1 lg:grid-cols-2">
                
                <div class="p-6 lg:p-8 border-b lg:border-b-0 lg:border-r border-slate-200 bg-slate-50">
                    <form method="POST" action="">
                        <div class="mb-6 grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div>
                                <label class="block text-sm font-semibold text-slate-700 mb-1">Target Stack</label>
                                <select name="framework" class="w-full bg-white border border-slate-300 text-slate-900 text-sm rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block p-2.5 shadow-sm">
                                    <option value="none">Plain (Empty Files)</option>
                                    <option value="ci4">CodeIgniter 4 (PHP)</option>
                                    <option value="laravel" selected>Laravel (PHP)</option>
                                    <option value="react">React (JS/TS)</option>
                                </select>
                            </div>
                        </div>

                        <div class="flex justify-between items-end mb-2">
                            <label for="tree_text" class="block text-sm font-semibold text-slate-700">Paste your text tree here:</label>
                        </div>
                        
                        <textarea name="tree_text" id="tree_text" rows="15" class="w-full bg-slate-900 text-green-400 p-4 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500 text-sm leading-relaxed shadow-inner" required></textarea>

                        <div class="mt-6 flex flex-col sm:flex-row gap-3 justify-end">
                            <button type="submit" name="action" value="bash" class="w-full sm:w-auto bg-slate-800 hover:bg-slate-900 text-white font-bold py-3 px-6 rounded-lg shadow-md transition-all duration-200 flex items-center justify-center gap-2">
                                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 9l3 3-3 3m5 0h3M5 20h14a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"></path></svg>
                                Export .sh Script
                            </button>
                            <button type="submit" name="action" value="zip" class="w-full sm:w-auto bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-3 px-6 rounded-lg shadow-md transition-all duration-200 flex items-center justify-center gap-2">
                                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"></path></svg>
                                Download ZIP
                            </button>
                        </div>
                    </form>
                </div>

                <div class="p-6 lg:p-8 flex flex-col h-full">
                    <h3 class="text-sm font-semibold text-slate-700 mb-3">Live Visual Preview:</h3>
                    <div class="flex-grow bg-white border border-slate-200 rounded-xl p-4 overflow-auto shadow-inner" style="min-height: 400px;" id="preview_container"></div>
                </div>

            </div>
        </div>
    </div>

    <script>
        const textArea = document.getElementById('tree_text');
        const previewContainer = document.getElementById('preview_container');
        const folderIcon = `<svg class="w-4 h-4 text-indigo-500 mr-2 shrink-0" fill="currentColor" viewBox="0 0 20 20"><path d="M2 6a2 2 0 012-2h5l2 2h5a2 2 0 012 2v6a2 2 0 01-2 2H4a2 2 0 01-2-2V6z"></path></svg>`;
        const fileIcon = `<svg class="w-4 h-4 text-slate-400 mr-2 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z"></path></svg>`;

        function updatePreview() {
            const text = textArea.value;
            previewContainer.innerHTML = '';
            let pathStack = [], renderedItems = 0;

            text.split('\n').forEach(line => {
                let cleaned = line.replace(/\s*[\(#].*$/, '').trimEnd();
                const match = cleaned.match(/^([│├└─\s ]*)(.*)$/);
                if (!match) return;

                let name = match[2].trim().replace(/\/$/, '').trim();
                if (!name) return;

                const visualIndent = match[1].length;
                const isFile = name.includes('.');

                while (pathStack.length > 0 && pathStack[pathStack.length - 1].indent >= visualIndent) pathStack.pop();
                pathStack.push({ name, indent: visualIndent });
                
                const level = pathStack.length - 1;
                const itemDiv = document.createElement('div');
                itemDiv.className = `flex items-center py-1.5 hover:bg-slate-50 rounded px-2 cursor-default transition-colors duration-150 ${isFile ? 'text-slate-600' : 'text-slate-900 font-medium'}`;
                itemDiv.style.paddingLeft = `${(level * 1.5) + 0.5}rem`;
                itemDiv.innerHTML = `${isFile ? fileIcon : folderIcon} <span class="truncate tracking-tight font-mono text-sm">${name}</span>`;
                previewContainer.appendChild(itemDiv);
                renderedItems++;
            });

            if (renderedItems === 0) {
                previewContainer.innerHTML = `<div class="flex flex-col items-center justify-center h-full text-slate-400 space-y-3"><svg class="w-12 h-12 text-slate-200" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"></path></svg><p class="text-sm">Start typing or paste a tree on the left...</p></div>`;
            }
        }

        textArea.addEventListener('input', updatePreview);
        updatePreview();
    </script>
</body>
</html>