<?php
/**
 * STRUCTIFY
 * Converts messy ASCII folder trees into a downloadable ZIP file.
 */

// --- BACKEND: Handle the Form Submission and ZIP Generation ---
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['tree_text'])) {
    
    $rawText = $_POST['tree_text'];
    $lines = explode("\n", $rawText);
    $structure = [];
    $pathStack = [];

    foreach ($lines as $line) {
        // 1. Clean the line: Remove trailing comments like "(Admin analytics)"
        $lineCleaned = preg_replace('/\s*\(.*$/', '', $line);
        $lineCleaned = rtrim($lineCleaned);

        // 2. Extract the prefix (tree symbols) and the actual name
        // This regex captures the symbols/spaces in group 1, and the folder/file name in group 2
        if (!preg_match('/^([│├└─\s ]*)(.*)$/u', $lineCleaned, $matches)) {
            continue; 
        }

        $prefix = $matches[1];
        $name = trim($matches[2]);
        
        // Remove trailing slashes from folder names (e.g., "app/" becomes "app")
        $name = rtrim($name, '/');

        if (empty($name)) continue;

        // 3. Calculate "Visual Depth" based on the prefix length
        $visualIndent = mb_strlen($prefix, 'UTF-8');
        $isFile = (strpos($name, '.') !== false);

        // 4. Manage the hierarchy stack
        // If the current indent is less than or equal to the last one, we moved up the tree
        while (!empty($pathStack) && end($pathStack)['indent'] >= $visualIndent) {
            array_pop($pathStack);
        }

        $currentNode = [
            'name' => $name,
            'indent' => $visualIndent,
            'is_file' => $isFile
        ];

        $pathStack[] = $currentNode;

        // Build the full path
        $fullPath = implode('/', array_column($pathStack, 'name'));
        
        $structure[] = [
            'path' => $fullPath,
            'is_file' => $isFile
        ];
    }

    // --- ZIP CREATION ---
    if (empty($structure)) {
        die("Could not parse any structure. Please check your text.");
    }

    $zip = new ZipArchive();
    $zipFileName = 'structify_project_' . time() . '.zip';
    
    // Create a local 'temp' folder to avoid system permission issues
    $tempDir = __DIR__ . '/temp';
    if (!is_dir($tempDir)) {
        mkdir($tempDir, 0777, true);
    }
    $tmpFilePath = $tempDir . '/' . $zipFileName;

    if ($zip->open($tmpFilePath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== TRUE) {
        die("Failed to create ZIP file on the server.");
    }

    foreach ($structure as $item) {
        if ($item['is_file']) {
            // Create empty file with a standard comment
            $zip->addFromString($item['path'], "<?php\n\n// File generated by Structify");
        } else {
            // Create empty directory
            $zip->addEmptyDir($item['path']);
        }
    }

    $zip->close();

    // --- FORCE DOWNLOAD ---
    header('Content-Type: application/zip');
    header('Content-Disposition: attachment; filename="' . basename($zipFileName) . '"');
    header('Content-Length: ' . filesize($tmpFilePath));
    header('Pragma: no-cache');
    header('Expires: 0');
    readfile($tmpFilePath);
    
    // Clean up temporary file
    unlink($tmpFilePath);
    exit;
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Structify - Turn Text into Folder Structures</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        textarea {
            font-family: 'Courier New', Courier, monospace;
            white-space: pre;
            overflow-wrap: normal;
            overflow-x: auto;
        }
    </style>
</head>
<body class="bg-slate-50 min-h-screen text-slate-800 font-sans selection:bg-indigo-200">

    <div class="max-w-5xl mx-auto px-6 py-12">
        <header class="mb-10 text-center">
            <h1 class="text-4xl font-extrabold tracking-tight text-slate-900 mb-2">Structify</h1>
            <p class="text-lg text-slate-600">Paste an ASCII folder tree, get a neat ZIP file. Simple.</p>
        </header>

        <div class="bg-white rounded-2xl shadow-xl overflow-hidden border border-slate-200">
            <div class="grid grid-cols-1 md:grid-cols-3">
                
                <div class="col-span-2 p-8 border-b md:border-b-0 md:border-r border-slate-200">
                    <form method="POST" action="">
                        <label for="tree_text" class="block text-sm font-semibold text-slate-700 mb-2">
                            Paste your folder tree here:
                        </label>
                        <textarea 
                            name="tree_text" 
                            id="tree_text" 
                            rows="18" 
                            class="w-full bg-slate-900 text-green-400 p-4 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500 text-sm leading-relaxed resize-y shadow-inner"
                            placeholder="root_project/
├── app/
│   ├── Controllers/
│   │   ├── Admin/
│   │   │   ├── Dashboard.php (Admin overview)
│   │   │   ├── Settings.php
│   ├── Models/
│   │   ├── UserModel.php
├── public/
│   ├── index.php" required></textarea>

                        <div class="mt-6 flex items-center justify-between">
                            <span class="text-xs text-slate-500">
                                * Automatically ignores comments in parentheses (like this).
                            </span>
                            <button 
                                type="submit" 
                                class="bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-3 px-8 rounded-lg shadow-md transition-all duration-200 transform hover:-translate-y-0.5">
                                Generate ZIP File
                            </button>
                        </div>
                    </form>
                </div>

                <div class="col-span-1 bg-slate-50 p-8">
                    <h3 class="text-lg font-bold text-slate-900 mb-4">How it works</h3>
                    <ul class="space-y-4 text-sm text-slate-600">
                        <li class="flex gap-3">
                            <svg class="w-5 h-5 text-indigo-500 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                            <span><strong>No configuration needed.</strong> It uses visual indentation (spaces, │, ├) to figure out which folders belong where.</span>
                        </li>
                        <li class="flex gap-3">
                            <svg class="w-5 h-5 text-indigo-500 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path></svg>
                            <span><strong>Smart Parsing.</strong> Files ending with extensions (like .php, .js) become empty files. Everything else becomes a folder.</span>
                        </li>
                        <li class="flex gap-3">
                            <svg class="w-5 h-5 text-indigo-500 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path></svg>
                            <span><strong>Clean Code.</strong> Extra descriptions added by AI are safely stripped out.</span>
                        </li>
                    </ul>
                </div>

            </div>
        </div>
    </div>

</body>
</html>