<?php
/**
 * STRUCTIFY - v2 (With Live Preview)
 * Converts messy ASCII folder trees into a downloadable ZIP file.
 */

// --- BACKEND: Handle the Form Submission and ZIP Generation ---
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['tree_text'])) {
    
    $rawText = $_POST['tree_text'];
    $lines = explode("\n", $rawText);
    $structure = [];
    $pathStack = [];

    foreach ($lines as $line) {
        $lineCleaned = preg_replace('/\s*\(.*$/', '', $line);
        $lineCleaned = rtrim($lineCleaned);

        if (!preg_match('/^([│├└─\s ]*)(.*)$/u', $lineCleaned, $matches)) {
            continue; 
        }

        $prefix = $matches[1];
        $name = trim($matches[2]);
        $name = rtrim($name, '/');

        if (empty($name)) continue;

        $visualIndent = mb_strlen($prefix, 'UTF-8');
        $isFile = (strpos($name, '.') !== false);

        while (!empty($pathStack) && end($pathStack)['indent'] >= $visualIndent) {
            array_pop($pathStack);
        }

        $currentNode = [
            'name' => $name,
            'indent' => $visualIndent,
            'is_file' => $isFile
        ];

        $pathStack[] = $currentNode;
        $fullPath = implode('/', array_column($pathStack, 'name'));
        
        $structure[] = [
            'path' => $fullPath,
            'is_file' => $isFile
        ];
    }

    if (empty($structure)) {
        die("Could not parse any structure. Please check your text.");
    }

    $zip = new ZipArchive();
    $zipFileName = 'structify_project_' . time() . '.zip';
    
    // Using the local temp folder fix we applied earlier!
    $tempDir = __DIR__ . '/temp';
    if (!is_dir($tempDir)) {
        mkdir($tempDir, 0777, true);
    }
    $tmpFilePath = $tempDir . '/' . $zipFileName;

    if ($zip->open($tmpFilePath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== TRUE) {
        die("Failed to create ZIP file on the server.");
    }

    foreach ($structure as $item) {
        if ($item['is_file']) {
            $zip->addFromString($item['path'], "<?php\n\n// File generated by Structify");
        } else {
            $zip->addEmptyDir($item['path']);
        }
    }
    $zip->close();

    header('Content-Type: application/zip');
    header('Content-Disposition: attachment; filename="' . basename($zipFileName) . '"');
    header('Content-Length: ' . filesize($tmpFilePath));
    header('Pragma: no-cache');
    header('Expires: 0');
    readfile($tmpFilePath);
    
    unlink($tmpFilePath);
    exit;
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Structify - Turn Text into Folder Structures</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        textarea {
            font-family: 'Courier New', Courier, monospace;
            white-space: pre;
            overflow-wrap: normal;
            overflow-x: auto;
        }
        /* Custom scrollbar for the preview area */
        #preview_container::-webkit-scrollbar { width: 8px; height: 8px; }
        #preview_container::-webkit-scrollbar-track { background: transparent; }
        #preview_container::-webkit-scrollbar-thumb { background: #cbd5e1; border-radius: 4px; }
        #preview_container::-webkit-scrollbar-thumb:hover { background: #94a3b8; }
    </style>
</head>
<body class="bg-slate-50 min-h-screen text-slate-800 font-sans selection:bg-indigo-200">

    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
        <header class="mb-8 text-center">
            <h1 class="text-4xl font-extrabold tracking-tight text-slate-900 mb-2">Structify</h1>
            <p class="text-lg text-slate-600">Paste an ASCII folder tree, get a neat ZIP file. Simple.</p>
        </header>

        <div class="bg-white rounded-2xl shadow-xl border border-slate-200 overflow-hidden">
            <div class="grid grid-cols-1 lg:grid-cols-2">
                
                <div class="p-6 lg:p-8 border-b lg:border-b-0 lg:border-r border-slate-200 bg-slate-50">
                    <form method="POST" action="">
                        <div class="flex justify-between items-end mb-3">
                            <label for="tree_text" class="block text-sm font-semibold text-slate-700">
                                Paste your text tree here:
                            </label>
                            <span class="text-xs text-slate-500 bg-slate-200 px-2 py-1 rounded">Auto-cleans comments</span>
                        </div>
                        
                        <textarea 
                            name="tree_text" 
                            id="tree_text" 
                            rows="20" 
                            class="w-full bg-slate-900 text-green-400 p-4 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500 text-sm leading-relaxed shadow-inner"
                            placeholder="root_project/
├── app/
│   ├── Controllers/
│   │   ├── Admin/
│   │   │   ├── Dashboard.php (Admin overview)
│   │   │   ├── Settings.php
│   ├── Models/
│   │   ├── UserModel.php
├── public/
│   ├── index.php" required></textarea>

                        <div class="mt-6 flex justify-end">
                            <button 
                                type="submit" 
                                class="w-full sm:w-auto bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-3 px-8 rounded-lg shadow-md transition-all duration-200 transform hover:-translate-y-0.5">
                                Generate ZIP File
                            </button>
                        </div>
                    </form>
                </div>

                <div class="p-6 lg:p-8 flex flex-col h-full">
                    <h3 class="text-sm font-semibold text-slate-700 mb-3">Live Visual Preview:</h3>
                    
                    <div class="flex-grow bg-white border border-slate-200 rounded-xl p-4 overflow-auto shadow-inner" style="min-height: 400px;" id="preview_container">
                        </div>
                </div>

            </div>
        </div>
    </div>

    <script>
        const textArea = document.getElementById('tree_text');
        const previewContainer = document.getElementById('preview_container');

        // SVG Icons
        const folderIcon = `<svg class="w-4 h-4 text-indigo-500 mr-2 shrink-0" fill="currentColor" viewBox="0 0 20 20"><path d="M2 6a2 2 0 012-2h5l2 2h5a2 2 0 012 2v6a2 2 0 01-2 2H4a2 2 0 01-2-2V6z"></path></svg>`;
        const fileIcon = `<svg class="w-4 h-4 text-slate-400 mr-2 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z"></path></svg>`;

        function updatePreview() {
            const text = textArea.value;
            const lines = text.split('\n');
            previewContainer.innerHTML = '';
            
            let pathStack = [];
            let renderedItems = 0;

            lines.forEach(line => {
                // 1. Strip comments
                let cleaned = line.replace(/\s*\(.*$/, '').trimEnd();
                
                // 2. Extract prefix and name
                const match = cleaned.match(/^([│├└─\s ]*)(.*)$/);
                if (!match) return;

                const prefix = match[1];
                let name = match[2].trim();
                name = name.replace(/\/$/, ''); // Remove trailing slashes

                if (!name) return;

                // 3. Calculate logical depth
                const visualIndent = prefix.length;
                const isFile = name.includes('.');

                // 4. Determine hierarchy level
                while (pathStack.length > 0 && pathStack[pathStack.length - 1].indent >= visualIndent) {
                    pathStack.pop();
                }

                pathStack.push({ name, indent: visualIndent });
                const level = pathStack.length - 1; // 0 is root

                // 5. Build the UI Element
                const itemDiv = document.createElement('div');
                itemDiv.className = `flex items-center py-1.5 hover:bg-slate-50 rounded px-2 cursor-default transition-colors duration-150 ${isFile ? 'text-slate-600' : 'text-slate-900 font-medium'}`;
                
                // Add padding based on depth level to create the visual tree hierarchy
                itemDiv.style.paddingLeft = `${(level * 1.5) + 0.5}rem`;
                
                itemDiv.innerHTML = `
                    ${isFile ? fileIcon : folderIcon} 
                    <span class="truncate tracking-tight font-mono text-sm">${name}</span>
                `;

                previewContainer.appendChild(itemDiv);
                renderedItems++;
            });

            // Empty state check
            if (renderedItems === 0) {
                previewContainer.innerHTML = `
                    <div class="flex flex-col items-center justify-center h-full text-slate-400 space-y-3">
                        <svg class="w-12 h-12 text-slate-200" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"></path></svg>
                        <p class="text-sm">Start typing or paste a tree on the left...</p>
                    </div>`;
            }
        }

        // Listen for typing/pasting and update instantly
        textArea.addEventListener('input', updatePreview);
        
        // Trigger once on page load to process any pre-filled placeholder text
        updatePreview();
    </script>
</body>
</html>